### ISSUE TITLE
available datasets of 'era5 land' do not include the soil moisture and tempearture data needed for the initial condition

### ISSUE THREAD

**Issue by yijianzeng** [EcoExtreML/zampy#55] opened 2024-02-12 20:21 UTC
![image](https://github.com/EcoExtreML/zampy/assets/10754705/57f8af28-c91c-4ead-9250-5f8f141f7132)
In the above figure, we see that the soil moisture/temperature data as needed for initial condition or 'soil_initial' are not available in zampy?

**Comment by BSchilperoort** [comment] 2024-02-13 07:13
Duplicate of #47 

Will be fixed by #53, but the [CDS has issues](https://confluence.ecmwf.int/display/CUSF/A+new+CDS+soon+to+be+launched+-+expect+some+disruptions) so testing/downloading is taking a long time.

**Closed by BSchilperoort** 2024-02-13 07:13 UTC
